name: clapnet
channels:
  - conda-forge
dependencies:
  - python=3.12.4
  - numpy=1.26.4
  - tqdm=4.66.4
  - librosa=0.10.2.post1
  - matplotlib=3.8.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - moviepy=1.0.3
  - pip
  - pip:
    - tensorflow-macos
    - opencv-python-headless
